version: '3.8'

services:
  tsarr-test:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=test
    volumes:
      - ../examples:/app/examples:ro
    command: bun run examples/test-single-movie.ts
    networks:
      - servarr-net

  # Test against mock Radarr service
  mock-radarr:
    image: mockserver/mockserver:5.15.0
    ports:
      - "7878:1080"
    environment:
      - MOCKSERVER_PROPERTY_FILE=/config/mockserver.properties
    volumes:
      - ./mock-config:/config
    networks:
      - servarr-net

networks:
  servarr-net:
    driver: bridge