export { BazarrClient } from './clients/bazarr';
export { LidarrClient } from './clients/lidarr';
export { ProwlarrClient } from './clients/prowlarr';
export { QBittorrentClient } from './clients/qbittorrent';
export { RadarrClient } from './clients/radarr';
export { ReadarrClient } from './clients/readarr';
export { SeerrClient } from './clients/seerr';
export { SonarrClient } from './clients/sonarr';
export * from './core/index';
export * as Bazarr from './generated/bazarr/index';
export * as Lidarr from './generated/lidarr/index';
export * as Prowlarr from './generated/prowlarr/index';
export * as QBittorrent from './generated/qbittorrent/index';
export * as Radarr from './generated/radarr/index';
export * as Readarr from './generated/readarr/index';
export * as Seerr from './generated/seerr/index';
export * as Sonarr from './generated/sonarr/index';
